import { readFileSync } from 'fs';
import { join } from 'path';
import { jest } from '@jest/globals';
import { JSDOM, VirtualConsole } from 'jsdom';

/**
 * DOM smoke tests for public/agent-ui.html.
 *
 * The page is a hand-written single-file UI (no build step), so it gets no
 * compile-time checking. These tests boot it in jsdom with a stubbed fetch and
 * drive the real user flows instead: send a message, expand a tool card, save
 * provider settings, persist and reopen history.
 *
 * Three behaviours here are regression guards for bugs that shipped once:
 *  1. `persistThread` looked the chat up in a second parse of localStorage and
 *     then saved the first one, so every assistant reply was silently dropped
 *     from history.
 *  2. The icon `<use href>` references must resolve to symbols in the sprite
 *     (the sprite is generated by `npm run ui:icons`).
 *  3. Rendered model output must stay escaped — the answer container only ever
 *     gets escaped text.
 */

const htmlPath = join(process.cwd(), 'public', 'agent-ui.html');
const html = readFileSync(htmlPath, 'utf8');

const ASSISTANT_REPLY = [
  'Here is the change I made.',
  '',
  '```ts',
  'export function cacheKey(id: string): string {',
  '  const prefix = "agent";',
  '  return prefix + ":" + id;',
  '}',
  '```',
  '',
  '- updated `cacheKey`',
  '',
  '<img src=x onerror="globalThis.__XSS = true">',
].join('\n');

type ApiCall = { url: string; method: string; body?: any };

/** A server extension snapshot, so each test can override just the part it cares about. */
function extensionSnapshot(overrides: Record<string, any> = {}) {
  return {
    skills: [], mcp: [], plugins: [],
    tools: ['read_file', 'write_file'],
    dirs: { skills: '/tmp/.agent/skills', plugins: '/tmp/.agent/plugins', mcpConfig: '/tmp/.agent/mcp.json' },
    ...overrides,
  };
}

async function bootUi(options?: { seedStorage?: Record<string, string>; asyncRun?: boolean; htmlRunError?: boolean }) {
  const calls: ApiCall[] = [];
  const settings: Record<string, any> = {
    model: 'claude-sonnet-4',
    baseUrl: 'https://relay.example/v1',
    hasApiKey: true,
    provider: 'anthropic',
    thinkingLevel: 'off',
  };
  const stored = new Map<string, string>();
  // Simulate a returning user: pre-seed what a previous session persisted.
  if (options?.seedStorage) {
    for (const [k, v] of Object.entries(options.seedStorage)) stored.set(k, v);
  }
  let failNextRun = false;
  const asyncRun = options?.asyncRun === true;
  const htmlRunError = options?.htmlRunError === true;
  let failNextInstall = false;

  const virtualConsole = new VirtualConsole();
  virtualConsole.on('jsdomError', (e: Error) => { throw e; });

  const dom = new JSDOM(html, {
    runScripts: 'dangerously',
    url: 'http://127.0.0.1:3000/agent-ui.html',
    pretendToBeVisual: true,
    virtualConsole,
    beforeParse(window: any) {
      const fakeStorage = {
        getItem: (k: string) => (stored.has(k) ? stored.get(k)! : null),
        setItem: (k: string, v: string) => { stored.set(k, String(v)); },
        removeItem: (k: string) => { stored.delete(k); },
        clear: () => stored.clear(),
        key: (i: number) => Array.from(stored.keys())[i] ?? null,
        get length() { return stored.size; },
      };
      Object.defineProperty(window, 'localStorage', { value: fakeStorage, configurable: true });

      window.fetch = (url: any, opts: any = {}) => {
        const u = String(url);
        const method = opts.method || 'GET';
        calls.push({ url: u, method, body: opts.body ? JSON.parse(opts.body) : undefined });

        const respond = (data: any) => Promise.resolve({ ok: true, json: () => Promise.resolve(data) });
        const respondBad = (data: any) => Promise.resolve({ ok: false, json: () => Promise.resolve(data) });

        if (u.includes('/api/agent/events')) {
          // EventSource is stubbed separately; a fetch to the SSE URL must never
          // be used by the page.
          return respondBad({ error: 'use EventSource' });
        }
        if (u.includes('/api/agent/run/job-async')) {
          return respond({
            jobId: 'job-async', status: 'completed', result: {
              response: ASSISTANT_REPLY,
              duration: 1234,
              toolExecutions: [
                { tool: 'read_file', input: { path: 'src/utils/CacheUtilities.ts' }, result: { success: true, output: 'file contents' }, duration: 12 },
                { tool: 'write_file', input: { path: 'src/utils/CacheUtilities.ts' }, result: { success: true, output: 'wrote 12 bytes' }, duration: 30, retryCount: 1 },
              ],
              stats: { totalCalls: 2, successCalls: 2, avgDuration: 40, iterations: 3, retries: 1, cacheHits: 2 },
              usage: { inputTokens: 1200, outputTokens: 340, totalTokens: 1540 },
              toolUsage: { read_file: 1, write_file: 1 },
            },
          });
        }
        if (u.includes('/api/agent/run')) {
          if (failNextRun) { failNextRun = false; return respondBad({ error: 'Agent request failed' }); }
          if (htmlRunError) {
            return Promise.resolve({
              ok: false,
              status: 504,
              headers: { get: () => 'text/html; charset=utf-8' },
              text: () => Promise.resolve('<!DOCTYPE html><title>Gateway timeout</title>'),
            });
          }
          if (asyncRun) return respond({ jobId: 'job-async', status: 'queued' });
          return respond({
            response: ASSISTANT_REPLY,
            duration: 1234,
            toolExecutions: [
              { tool: 'read_file', input: { path: 'src/utils/CacheUtilities.ts' }, result: { success: true, output: 'file contents' }, duration: 12 },
              { tool: 'write_file', input: { path: 'src/utils/CacheUtilities.ts' }, result: { success: true, output: 'wrote 12 bytes' }, duration: 30, retryCount: 1 },
            ],
            stats: { totalCalls: 2, successCalls: 2, avgDuration: 40, iterations: 3, retries: 1, cacheHits: 2 },
            usage: { inputTokens: 1200, outputTokens: 340, totalTokens: 1540 },
            toolUsage: { read_file: 1, write_file: 1 },
          });
        }
        if (u.includes('/api/agent/settings') && method === 'PUT') {
          const body = JSON.parse(opts.body);
          if (body.model !== undefined) settings.model = body.model;
          if (body.baseUrl !== undefined) settings.baseUrl = body.baseUrl;
          if (body.apiKey) settings.hasApiKey = true;
          if (body.clearApiKey) settings.hasApiKey = false;
          if (body.provider !== undefined) settings.provider = body.provider;
          if (body.thinkingLevel !== undefined) settings.thinkingLevel = body.thinkingLevel;
          return respond({ ...settings, provider: settings.provider, thinkingLevel: settings.thinkingLevel });
        }
        if (u.includes('/api/agent/settings')) {
          return respond({ ...settings, provider: settings.provider, thinkingLevel: settings.thinkingLevel });
        }
        if (u.includes('/api/agent/status')) {
          return respond({
            status: 'idle', model: '', provider: 'anthropic',
            tools: Array.from({ length: 66 }, (_, i) => ({ name: 'tool_' + i, description: '' })),
            iterations: 0, historyLength: 0,
          });
        }
        if (u.includes('/api/agent/report')) {
          return respond({ overview: { totalExecutions: 2, totalSuccess: 2, avgExecutionTime: 40 }, slowestTools: [], modelCalls: 7 });
        }
        if (u.includes('/api/agent/clear')) return respond({ success: true });
        if (u.includes('/api/agent/extensions/skills/')) {
          return respond({ name: 'demo', content: '---\nname: demo\n---\n\n# Demo skill\n', files: ['SKILL.md'] });
        }
        if (u.includes('/api/agent/extensions/install')) {
          if (failNextInstall) { failNextInstall = false; return respondBad({ error: 'Nothing installable at that URL' }); }
          return respond({
            kind: 'skill', name: 'demo', files: 2, installed: ['SKILL.md'],
            snapshot: extensionSnapshot({ skills: [{ name: 'demo', description: 'A demo skill', path: '/tmp/skills/demo', files: 2, bytes: 120, source: { kind: 'github', repo: 'o/r' } }] }),
          });
        }
        if (u.includes('/api/agent/extensions/mcp')) {
          return respond({ snapshot: extensionSnapshot({ mcp: [{ name: 'fake', command: 'node', args: ['server.mjs'], enabled: true, status: 'connected', tools: ['echo'] }] }) });
        }
        if (u.includes('/api/agent/extensions/plugins/')) {
          return respond({ plugin: { name: 'demo' }, snapshot: extensionSnapshot() });
        }
        if (u.includes('/api/agent/extensions/')) {
          return respond({ snapshot: extensionSnapshot() });
        }
        if (u.includes('/api/agent/extensions')) return respond(extensionSnapshot());
        return respond({});
      };

      // Live activity arrives over SSE; record the frames the page receives.
      const events: any[] = [];
      (window as any).__events = events;
      class FakeEventSource {
        onmessage: ((e: any) => void) | null = null;
        onerror: ((e: any) => void) | null = null;
        closed = false;
        constructor(public url: string) { (window as any).__eventSource = this; }
        close() { this.closed = true; }
        emit(payload: any) { events.push(payload); if (this.onmessage) this.onmessage({ data: JSON.stringify(payload) }); }
      }
      (window as any).EventSource = FakeEventSource;

      window.alert = () => {};
      window.prompt = (text: string) => {
        if (text === 'Enter the Agent CLI access key') return 'test-access-key';
        throw new Error('unexpected window.prompt: ' + text);
      };
    },
  });

  const doc = dom.window.document;
  const $ = (id: string) => doc.getElementById(id)!;
  const tick = (n = 1) => new Promise(r => setTimeout(r, 20 * n));
  const click = (node: any) => node.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true, cancelable: true }));
  const submit = () => $('composer').dispatchEvent(new dom.window.Event('submit', { bubbles: true, cancelable: true }));
  const type = (value: string) => { const ta = $('messageInput'); ta.value = value; ta.dispatchEvent(new dom.window.Event('input')); };

  await tick(3);

  return {
    window: dom.window, doc, $, tick, click, submit, type, calls, settings,
    fail: () => { failNextRun = true; },
    failInstall: () => { failNextInstall = true; },
    emitEvent: (payload: any) => (dom.window as any).__eventSource?.emit(payload),
    openEventSource: () => (dom.window as any).__eventSource,
  };
}

describe('web UI (agent-ui.html)', () => {
  jest.setTimeout(30000);

  it('inlines a working icon sprite (npm run ui:icons)', async () => {
    const { doc } = await bootUi();
    const symbols = doc.querySelectorAll('svg.sprite symbol');
    expect(symbols.length).toBeGreaterThanOrEqual(20);
    const uses = Array.from(doc.querySelectorAll('use')) as any[];
    expect(uses.length).toBeGreaterThan(20);
    for (const u of uses) {
      const id = (u.getAttribute('href') || '').replace('#', '');
      expect(doc.getElementById(id)).not.toBeNull();
    }
    // Nothing left hand-inlined in the chrome (all icons come from the sprite).
    expect(doc.querySelectorAll('.sidebar svg path, .topbar svg path').length).toBe(0);
  });

  it('boots: model, tool count, status and the empty state', async () => {
    const { $, doc } = await bootUi();
    expect($('modelName').textContent).toBe('claude-sonnet-4');
    expect($('heroTitle').textContent).toBe('claude-sonnet-4');
    expect($('toolCount').textContent).toBe('66');
    expect($('statusPill').className).toContain('ready');
    expect($('emptyState').hidden).toBe(false);
    expect($('threadHost').hidden).toBe(true);
    expect(doc.querySelectorAll('.suggestion').length).toBe(4);
    expect($('sendBtn').disabled).toBe(true);
    // Unknown metrics are reported honestly, never as a fake zero.
    expect($('mCached').textContent).toBe('—');
    expect($('mRetry').textContent).toBe('—');
    expect($('mSuccess').textContent).toBe('—');
  });

  it('sends a message and renders the reply, tools, code and metrics', async () => {
    const { $, doc, tick, submit, type, click, calls } = await bootUi();

    type('hello agent');
    expect($('sendBtn').disabled).toBe(false);
    submit();
    await tick();
    expect($('emptyState').hidden).toBe(true);
    expect($('threadHost').hidden).toBe(false);
    const run = calls.filter(c => c.url.includes('/api/agent/run')).pop()!;
    expect(run.body.config.cache).toBe(true);
    expect(run.body.config.validation).toBe(true);
    await tick(3);

    expect(doc.querySelectorAll('.answer').length).toBe(1);

    // code block: fence removed, highlight spans balanced
    const code = doc.querySelector('.codeblock code')!;
    expect(code).not.toBeNull();
    expect(code.textContent).toContain('"agent"');
    expect(doc.querySelector('.answer')!.innerHTML).not.toContain('```');
    expect(doc.querySelectorAll('.tool-card').length).toBe(2);
    // real tool fields (duration / retryCount), not guessed ones
    expect(doc.querySelectorAll('.tool-card')[1].textContent).toContain('retry 1');

    // collapsible tool card
    const head = doc.querySelector('.tool-head')!;
    expect(doc.querySelector('.tool-card')!.className).not.toContain('open');
    click(head);
    expect(doc.querySelector('.tool-card')!.className).toContain('open');
    expect(head.getAttribute('aria-expanded')).toBe('true');
    expect(doc.querySelector('.tool-pre')!.textContent).toContain('src/utils/CacheUtilities.ts');

    // result card derives its file path from the tool input
    expect(doc.querySelector('.rc-path')!.textContent).toBe('src/utils/CacheUtilities.ts');
    expect(doc.querySelector('.rc-status')!.textContent).toContain('Success');

    // metrics painted from the run response
    expect($('mTotal').textContent).toBe('2');
    expect($('mSuccess').textContent).toBe('100%');
    expect($('mIter').textContent).toBe('3');
    expect($('mRetry').textContent).toBe('1');
    expect($('mCached').textContent).toBe('2');
    expect($('mInput').textContent).toBe('1,200');
    expect($('mOutput').textContent).toBe('340');
    expect($('mTotalTokens').textContent).toBe('1,540');
    expect($('statusPill').className).toContain('ready');
  });

  it('waits for a background job instead of holding the original request open', async () => {
    const { $, doc, tick, submit, type, calls } = await bootUi({ asyncRun: true });
    type('build a landing page');
    submit();
    await tick(50);

    const starts = calls.filter(c => c.url === '/api/agent/run' && c.method === 'POST');
    expect(starts).toHaveLength(1);
    expect(calls.some(c => c.url === '/api/agent/run/job-async')).toBe(true);
    expect(doc.querySelectorAll('.answer').length).toBe(1);
    expect($('statusPill').className).toContain('ready');
  });

  it('turns an HTML proxy error into a useful message instead of a JSON parse error', async () => {
    const { doc, tick, submit, type } = await bootUi({ htmlRunError: true });
    type('build a landing page');
    submit();
    await tick(4);

    const answer = doc.querySelector('.answer')!.textContent || '';
    expect(answer).toMatch(/temporarily unavailable/i);
    expect(answer).not.toMatch(/Unexpected token/i);
    expect(answer).not.toMatch(/DOCTYPE/i);
  });

  it('keeps model output escaped (no HTML injection)', async () => {
    const { doc, tick, submit, type, window } = await bootUi();
    type('anything');
    submit();
    await tick(4);
    expect((window as any).__XSS).toBeUndefined();
    expect(doc.querySelector('.answer img')).toBeNull();
    expect(doc.querySelectorAll('script').length).toBe(1);
  });

  it('persists the whole thread, including the assistant reply, and reopens it', async () => {
    const { $, doc, tick, submit, type, click, window } = await bootUi();
    type('hello agent');
    submit();
    await tick(4);

    // regression: the assistant reply used to be dropped from storage
    const raw = (window as any).localStorage.getItem('agent-cli.chats.v2');
    expect(raw).toBeTruthy();
    const chats = JSON.parse(raw!);
    expect(chats.length).toBe(1);
    expect(chats[0].thread.map((m: any) => m.role)).toEqual(['user', 'assistant']);
    expect(chats[0].options.validation).toBe(true);
    expect(doc.querySelectorAll('.answer').length).toBe(1);

    click($('navHistory'));
    await tick();
    expect($('historyList').querySelectorAll('.history-row').length).toBe(1);
    expect(doc.querySelector('.history-time')).not.toBeNull();

    // search uses an inline input, never window.prompt
    click($('navSearch'));
    expect($('searchBox').hidden).toBe(false);
    $('searchInput').value = 'zzz';
    $('searchInput').dispatchEvent(new (window as any).Event('input'));
    expect($('historyList').textContent).toMatch(/No chats match/);
    $('searchInput').value = 'hello';
    $('searchInput').dispatchEvent(new (window as any).Event('input'));
    expect($('historyList').querySelectorAll('.history-row').length).toBe(1);

    click($('newChatBtn'));
    await tick();
    expect($('emptyState').hidden).toBe(false);
    expect(doc.querySelectorAll('.msg').length).toBe(0);

    click($('historyList').querySelector('.history-open'));
    await tick();
    expect(doc.querySelectorAll('.answer').length).toBe(1);
    expect($('composerHostDocked').contains($('composer'))).toBe(true);
  });

  it('deletes a saved chat', async () => {
    const { $, doc, tick, submit, type, click, window } = await bootUi();
    // create a chat first so there is something to delete
    type('to delete');
    submit();
    await tick(4);
    expect(doc.querySelectorAll('.msg').length).toBeGreaterThan(0);
    expect(JSON.parse((window as any).localStorage.getItem('agent-cli.chats.v2') || '[]').length).toBe(1);

    click($('navHistory'));
    await tick(2);
    expect($('historyList').querySelectorAll('.history-row').length).toBe(1);
    click($('historyList').querySelector('.history-del'));
    await tick(2);
    expect(JSON.parse((window as any).localStorage.getItem('agent-cli.chats.v2') || '[]').length).toBe(0);
  });

  it('edits provider settings without ever exposing the API key', async () => {
    const { $, doc, tick, click, submit, type, calls, window } = await bootUi();

    type('seed');
    submit();
    await tick(4);

    click($('settingsBtn'));
    await tick();
    expect($('settingsOverlay').hidden).toBe(false);
    expect($('setModel').value).toBe('claude-sonnet-4');
    expect($('setBaseUrl').value).toBe('https://relay.example/v1');
    expect($('setApiKey').type).toBe('password');
    expect($('setApiKey').value).toBe('');
    expect($('apiKeyBadge').textContent).toBe('configured');

    $('setBaseUrl').value = 'https://relay.example/v2';
    $('setApiKey').value = 'sk-test-not-a-real-key';
    $('settingsForm').dispatchEvent(new (window as any).Event('submit', { bubbles: true, cancelable: true }));
    await tick(3);

    const put = calls.filter(c => c.url.includes('/api/agent/settings') && c.method === 'PUT').pop()!;
    expect(put.body.baseUrl).toBe('https://relay.example/v2');
    expect(put.body.apiKey).toBe('sk-test-not-a-real-key');
    expect($('settingsMsg').textContent).toMatch(/Saved/);
    expect($('setApiKey').value).toBe('');
    // the key is never rendered back and never stored client-side
    expect(doc.body.innerHTML).not.toContain('sk-test-not-a-real-key');
    expect(JSON.stringify({ ...window.localStorage })).not.toContain('sk-test');

    click($('clearKeyBtn'));
    await tick();
    expect($('apiKeyBadge').textContent).toBe('missing');
    click($('settingsClose'));
    expect($('settingsOverlay').hidden).toBe(true);

    // the header follows the saved model
    expect($('modelName').textContent).toBe('claude-sonnet-4');
    expect(doc.querySelectorAll('.toast').length).toBeGreaterThan(0);
  });

  it('opens the metrics panel with provider info and the tool list', async () => {
    const { $, tick, click } = await bootUi();
    click($('panelBtn'));
    await tick(2);
    expect($('metricsPanel').hidden).toBe(false);
    expect($('app').className).toContain('with-panel');
    expect($('providerInfo').textContent).toMatch(/base url/);
    expect($('providerInfo').textContent).toMatch(/configured/);
    expect($('registeredTools').querySelectorAll('.panel-row').length).toBe(21);
    click($('panelClose'));
    expect($('metricsPanel').hidden).toBe(true);
    expect($('app').className).not.toContain('with-panel');
  });

  it('surfaces a failed run as an error message plus a toast', async () => {
    const { $, doc, tick, submit, type, fail } = await bootUi();
    fail();
    type('boom');
    submit();
    await tick(4);
    expect(doc.querySelectorAll('.msg.user').length).toBe(1);
    expect(doc.querySelector('.answer')!.textContent).toMatch(/Agent request failed/);
    expect(doc.querySelector('.typing')).toBeNull();
    expect($('statusPill').className).toContain('error');
    expect($('statusText').textContent).toBe('Error');
    expect($('sendBtn').disabled).toBe(true);
    expect($('sendBtn').className).not.toContain('busy');
    const toasts = Array.from(doc.querySelectorAll('.toast')) as any[];
    expect(toasts.some(t => /Agent request failed/.test(t.textContent))).toBe(true);
  });

  it('collapses and expands the sidebar, remembering the state', async () => {
    const { $, doc, click, tick, window } = await bootUi();
    const app = $('app');
    const sidebar = doc.querySelector('.sidebar') as any;
    expect(sidebar).not.toBeNull();

    click($('sidebarToggle'));
    await tick(1);
    expect(app.className).toContain('sidebar-collapsed');
    expect((window as any).localStorage.getItem('agent-cli.sidebar-collapsed')).toBe('1');
    expect($('sidebarToggle').getAttribute('aria-expanded')).toBe('false');

    click($('sidebarToggle'));
    await tick(1);
    expect(app.className).not.toContain('sidebar-collapsed');
    expect((window as any).localStorage.getItem('agent-cli.sidebar-collapsed')).toBeNull();
  });

  it('restores a collapsed sidebar from storage at boot', async () => {
    const { window } = await bootUi();
    (window as any).localStorage.setItem('agent-cli.sidebar-collapsed', '1');
    const second = await bootUi({ seedStorage: { 'agent-cli.sidebar-collapsed': '1' } });
    expect(second.$('app').className).toContain('sidebar-collapsed');
  });

  it('toggles the theme and remembers it', async () => {
    const { $, doc, click, window } = await bootUi();
    expect(doc.documentElement.getAttribute('data-theme')).toBe('dark');
    click($('themeBtn'));
    expect(doc.documentElement.getAttribute('data-theme')).toBe('light');
    expect((window as any).localStorage.getItem('agent-cli.theme')).toBe('light');
    click($('themeBtn'));
    expect(doc.documentElement.getAttribute('data-theme')).toBe('dark');
    expect($('themeBtn').getAttribute('aria-label')).toMatch(/theme/i);
  });

  it('saves provider, model and thinking level from the model popover', async () => {
    const { $, doc, click, tick, calls } = await bootUi();
    click($('modelBtn'));
    await tick(1);
    const popover = $('modelPopover');
    expect(popover.hidden).toBe(false);

    $('pickProvider').value = 'openai';
    $('pickThinking').value = 'high';
    $('setModel').value = 'gpt-5-codex';
    $('modelPopoverForm').dispatchEvent(new (doc.defaultView as any).Event('submit', { bubbles: true, cancelable: true }));
    await tick(3);

    const put = calls.filter(c => c.url.includes('/api/agent/settings') && c.method === 'PUT').pop()!;
    expect(put.body.provider).toBe('openai');
    expect(put.body.thinkingLevel).toBe('high');
    expect(put.body.model).toBe('gpt-5-codex');
    expect(popover.hidden).toBe(true);
    expect($('modelName').textContent).toBe('gpt-5-codex');
  });

  it('remembers the chosen channel across reloads', async () => {
    const first = await bootUi();
    first.$('pickProvider').value = 'openai';
    first.$('pickThinking').value = 'medium';
    first.$('setModel').value = 'gpt-4.1';
    first.$('modelBtn').click();
    await first.tick(1);
    first.$('modelPopoverForm').dispatchEvent(new (first.window as any).Event('submit', { bubbles: true, cancelable: true }));
    await first.tick(3);

    const stored = JSON.parse((first.window as any).localStorage.getItem('agent-cli.profile') || '{}');
    expect(stored.provider).toBe('openai');
    expect(stored.thinkingLevel).toBe('medium');
    expect(stored.model).toBe('gpt-4.1');
  });

  it('opens a docs overlay from Help instead of a toast', async () => {
    const { $, doc, click, tick } = await bootUi();
    click($('navHelp'));
    await tick(1);
    const docs = $('docsOverlay');
    expect(docs.hidden).toBe(false);
    expect(docs.textContent).toMatch(/Enter/);
    expect(docs.textContent).toMatch(/Shift\+Enter/);
    expect(doc.querySelectorAll('.toast').length).toBe(0);
    click($('docsClose'));
    expect(docs.hidden).toBe(true);
  });

  it('keeps the composer mounted and usable after the first message', async () => {
    const { $, doc, submit, type, tick } = await bootUi();
    type('first');
    submit();
    await tick(4);
    expect($('threadHost').hidden).toBe(false);
    expect($('composerHostDocked').hidden).toBe(false);
    expect($('composerHostDocked').contains($('composer'))).toBe(true);
    expect($('messageInput').value).toBe('');
    // and it still works for a follow-up message
    type('second');
    expect($('sendBtn').disabled).toBe(false);
    submit();
    await tick(4);
    expect(doc.querySelectorAll('.msg.user').length).toBe(2);
  });

  it('sends attachments with the message and shows them in the transcript', async () => {
    const { $, doc, window, submit, type, tick, calls } = await bootUi();
    const png = Buffer.from('89504e470d0a1a0a', 'hex').toString('base64');
    const input = $('fileInput') as HTMLInputElement;
    Object.defineProperty(input, 'files', { value: [{ name: 'shot.png', type: 'image/png' }, { name: 'notes.md', type: 'text/markdown' }] });
    window.FileReader = class {
      result = '';
      onload: any = null;
      onerror: any = null;
      readAsDataURL() {
        const anyFile: any = (input as any).files[0];
        this.result = 'data:' + anyFile.type + ';base64,' + png;
        if (this.onload) this.onload({ target: this });
      }
    } as any;
    window.File = class {
      name: string; type: string;
      constructor(name: string, type: string) { this.name = name; this.type = type; }
    } as any;
    window.btoa = (s: string) => Buffer.from(s, 'binary').toString('base64');
    window.atob = (s: string) => Buffer.from(s, 'base64').toString('binary');

    ($('chipAttach') as any).click();
    await tick(2);
    type('look at these');
    submit();
    await tick(5);

    const run = calls.filter(c => c.url.includes('/api/agent/run')).pop()!;
    expect(Array.isArray(run.body.attachments)).toBe(true);
    expect(run.body.attachments.length).toBe(2);
    expect(run.body.attachments[0].name).toBe('shot.png');
    expect(run.body.attachments[0].mimeType).toBe('image/png');
    expect(run.body.attachments[0].data.length).toBeGreaterThan(0);
    expect(run.body.attachments[1].name).toBe('notes.md');
    expect(doc.querySelector('.msg.user .attach-chip').textContent).toMatch(/shot\.png/);
  });

  it('shows live tool activity from the server event stream', async () => {
    const { $, doc, window, submit, type, tick, openEventSource, emitEvent } = await bootUi();
    type('run something');
    submit();
    await tick(1);
    // The page subscribes while the run is in flight.
    const es = openEventSource();
    expect(es).toBeTruthy();
    es.emit({ type: 'toolStart', tool: 'read_file', id: 'a1', input: { path: 'README.md' } });
    await tick(1);
    expect(doc.querySelector('.activity-feed')).not.toBeNull();
    expect(doc.querySelector('.activity-feed').textContent).toMatch(/read_file/);
    es.emit({ type: 'toolEnd', tool: 'read_file', duration: 42, success: true });
    await tick(1);
    es.emit({ type: 'tokenUsage', inputTokens: 10, outputTokens: 5, totalTokens: 15 });
    await tick(1);
    expect((window as any).__events.length).toBeGreaterThan(2);
    expect($('liveTokens').textContent).toMatch(/15|10/);
  });

  it('opens the metrics panel from the topbar button and shows token detail', async () => {
    const { $, doc, submit, type, tick, click } = await bootUi();
    type('hi');
    submit();
    await tick(4);
    click($('panelBtn'));
    await tick(2);
    expect($('metricsPanel').hidden).toBe(false);
    expect($('mInput').textContent).toBe('1,200');
    expect($('mOutput').textContent).toBe('340');
    expect($('mTotalTokens').textContent).toBe('1,540');
    expect(doc.querySelectorAll('.stat').length).toBeGreaterThanOrEqual(9);
  });

  it('counts model calls in the panel and the token detail', async () => {
    const { $, doc, submit, type, tick, click } = await bootUi();
    type('hi');
    submit();
    await tick(4);
    click($('panelBtn'));
    await tick(2);
    // The server counts one model call per provider round trip and reports it on
    // both /report and /run; the panel must not leave the stat blank.
    expect($('mCalls').textContent).toBe('7');
    expect($('tokenInfo').textContent).toMatch(/model calls/);
    expect(doc.querySelectorAll('.stat').length).toBeGreaterThanOrEqual(10);
  });

  it('keeps the running token total when the server sends per-call usage', async () => {
    // Regression guard: the SSE frame carries this call's slice *and* the running
    // session total. Painting the slice made the panel look like it had forgotten
    // every earlier call.
    const { $, submit, type, tick, openEventSource } = await bootUi();
    type('go');
    submit();
    await tick(1);
    const es = openEventSource();
    es.emit({ type: 'tokenUsage', inputTokens: 900, outputTokens: 100, totalTokens: 1000, session: { inputTokens: 900, outputTokens: 100, totalTokens: 1000 } });
    await tick(1);
    expect($('mTotalTokens').textContent).toBe('1,000');
    es.emit({ type: 'tokenUsage', inputTokens: 40, outputTokens: 10, totalTokens: 50, session: { inputTokens: 940, outputTokens: 110, totalTokens: 1050 } });
    await tick(1);
    expect($('mTotalTokens').textContent).toBe('1,050');
    expect($('mInput').textContent).toBe('940');
    expect($('mOutput').textContent).toBe('110');
    expect($('liveTokens').textContent).toBe('1,050 tokens');
  });

  it('shows the metrics panel as a drawer instead of hiding it under 1180px', async () => {
    // Regression guard: `.panel { display: none }` at <=1180px meant the Tools and
    // Metrics buttons toggled state that was never painted on a phone or a small
    // laptop window.
    const { $, tick, click } = await bootUi();
    expect(html).toMatch(/\.app\.with-panel \.panel \{ transform: none; \}/);
    expect(html).not.toMatch(/@media \(max-width: 1180px\)[\s\S]*?\.panel \{ display: none; \}/);
    expect(html).toMatch(/\.app\.with-panel \.panel-backdrop/);
    click($('panelBtn'));
    await tick(2);
    expect($('app').className).toContain('with-panel');
    // The backdrop closes the drawer, like the sidebar's does.
    click($('panelBackdrop'));
    await tick(1);
    expect($('metricsPanel').hidden).toBe(true);
    expect($('app').className).not.toContain('with-panel');
  });

  it('refreshes the metrics after a failed run', async () => {
    const { $, calls, tick, submit, type, fail } = await bootUi();
    fail();
    type('boom');
    submit();
    await tick(4);
    expect($('statusPill').className).toContain('error');
    // A failed run still costs tokens and may have run tools first.
    expect(calls.filter(c => c.url.includes('/api/agent/report')).length).toBeGreaterThan(0);
  });

  it('puts the profile and its settings key button at the bottom-left', async () => {
    const { $, doc, click, tick } = await bootUi();
    const foot = doc.querySelector('.side-foot')!;
    expect(foot.contains($('profileBtn'))).toBe(true);
    expect(foot.contains($('profileKeyBtn'))).toBe(true);
    expect(foot.querySelectorAll('button').length).toBeGreaterThanOrEqual(2);
    click($('profileKeyBtn'));
    await tick(1);
    expect($('settingsOverlay').hidden).toBe(false);
  });

  it('opens the extensions hub from the Tools button and lists what is installed', async () => {
    const { $, doc, tick, click } = await bootUi();
    // The Tools nav item used to just open the metrics panel; it is now the
    // place where skills, MCP servers and plugins are managed.
    click($('navTools'));
    await tick(3);
    expect($('extOverlay').hidden).toBe(false);
    expect($('extTitle').textContent).toMatch(/Tools/);
    expect($('extSkillCount').textContent).toBe('0');
    expect($('extToolCount').textContent).toBe('2');
    expect($('extSkills').textContent).toMatch(/No skills installed yet/);
    expect($('extTools').textContent).toMatch(/read_file/);
    expect($('mcpConfigPath').textContent).toMatch(/mcp\.json/);

    // Tabs switch panes. Every pane id is plural while the kind is not — the
    // mismatch is easy to introduce and leaves two panes visible at once.
    click($('extTabMcp'));
    await tick(1);
    expect($('extPaneMcp').hidden).toBe(false);
    expect($('extPaneSkills').hidden).toBe(true);
    expect($('extTabMcp').className).toContain('on');
    expect($('extTabSkills').className).not.toContain('on');

    click($('extTabPlugins'));
    await tick(1);
    expect($('extPanePlugins').hidden).toBe(false);
    expect($('extPaneMcp').hidden).toBe(true);

    click($('extTabTools'));
    await tick(1);
    expect($('extPaneTools').hidden).toBe(false);
    expect($('extPanePlugins').hidden).toBe(true);

    click($('extTabSkills'));
    await tick(1);
    expect($('extPaneSkills').hidden).toBe(false);
    expect($('extPaneTools').hidden).toBe(true);

    click($('extOk'));
    expect($('extOverlay').hidden).toBe(true);
  });

  it('installs an extension from a GitHub URL and shows the result', async () => {
    const { $, doc, calls, tick, click } = await bootUi();
    click($('navTools'));
    await tick(3);
    $('extUrl').value = 'https://github.com/o/r/tree/main/skills/demo';
    $('extKind').value = 'auto';
    click($('extInstallBtn'));
    await tick(3);

    const install = calls.filter(c => c.url.includes('/api/agent/extensions/install')).pop()!;
    expect(install.method).toBe('POST');
    expect(install.body.url).toBe('https://github.com/o/r/tree/main/skills/demo');
    expect(install.body.kind).toBeUndefined(); // "Detect" leaves the choice to the server
    expect($('extMsg').textContent).toMatch(/Installed skill "demo"/);
    expect($('extSkillCount').textContent).toBe('1');
    expect($('extSkills').textContent).toMatch(/demo/);
    expect(doc.querySelectorAll('.toast').length).toBeGreaterThan(0);
  });

  it('sends an explicit kind when the user picks one, and surfaces a failed install', async () => {
    const { $, tick, click, failInstall } = await bootUi();
    click($('navTools'));
    await tick(3);
    failInstall();
    $('extUrl').value = 'https://github.com/o/r';
    $('extKind').value = 'plugin';
    click($('extInstallBtn'));
    await tick(3);
    expect($('extMsg').textContent).toMatch(/Nothing installable/);
    expect($('extMsg').className).toContain('bad');
  });

  it('refuses to install without a URL', async () => {
    const { $, tick, click } = await bootUi();
    click($('navTools'));
    await tick(3);
    click($('extInstallBtn'));
    await tick(1);
    expect($('extMsg').textContent).toMatch(/Paste a GitHub URL/);
  });

  it('adds an MCP server with name, command and arguments', async () => {
    const { $, calls, tick, click } = await bootUi();
    click($('navTools'));
    await tick(3);
    click($('extTabMcp'));
    await tick(1);
    $('mcpName').value = 'fake';
    $('mcpCommand').value = 'node';
    $('mcpArgs').value = 'server.mjs --flag';
    click($('mcpAddBtn'));
    await tick(3);

    const add = calls.filter(c => c.url.endsWith('/api/agent/extensions/mcp')).pop()!;
    expect(add.method).toBe('POST');
    expect(add.body).toEqual({ name: 'fake', command: 'node', args: ['server.mjs', '--flag'] });
    expect($('extMcp').textContent).toMatch(/connected/);
    expect($('extMcpCount').textContent).toBe('1');
    expect($('mcpName').value).toBe('');
  });

  it('shows a skill\'s SKILL.md in the viewer', async () => {
    const { $, doc, tick, click } = await bootUi();
    click($('navTools'));
    await tick(3);
    // Install first so there is a skill row with a View button.
    $('extUrl').value = 'https://github.com/o/r/tree/main/skills/demo';
    click($('extInstallBtn'));
    await tick(3);
    const view = Array.from(doc.querySelectorAll('#extSkills button') as any).find((b: any) => /View/.test(b.textContent!)) as any;
    expect(view).toBeDefined();
    click(view);
    await tick(2);
    expect($('extSkills').querySelector('.ext-pre')!.textContent).toMatch(/Demo skill/);
    const back = Array.from(doc.querySelectorAll('#extSkills button') as any).find((b: any) => /Back/.test(b.textContent!)) as any;
    click(back);
    await tick(1);
    expect($('extSkills').querySelector('.ext-pre')).toBeNull();
  });

  it('declares Thai-capable fonts and uses them in the stack', () => {
    const { doc } = { doc: null } as any;
    expect(html).toMatch(/@font-face/);
    expect(html).toMatch(/Mitr/);
    expect(html).toMatch(/font-family:[^;]*Helvetica/);
  });

  it('keeps the bottom-docked composer inside the usable viewport', () => {
    // Regression guard: 100vh is the *large* viewport on a phone, so a composer
    // docked at the bottom of a 100vh shell ended up underneath the browser bars
    // and the send box looked like it had vanished.
    expect(html).toMatch(/interactive-widget=resizes-content/);
    expect(html).toMatch(/height:\s*100dvh/);
    expect(html).toMatch(/height:\s*100vh;\s*\n\s*height:\s*100dvh/);
    expect(html).toMatch(/padding:[^;]*env\(safe-area-inset-bottom/);
  });
});
